"""Phase 17 canonical ablation contracts."""

from .outputs import (
    ArtifactIndex,
    ArtifactIndexEntry,
    CheckpointKind,
    CheckpointManifest,
    DatasetRole,
    EquivalenceManifest,
    HistoryManifest,
    HistoryRow,
    LossComponentRecord,
    OutputIdentity,
    PredictionRecord,
    TargetMonitoring,
    TrainingStage,
)
from .registry import get_ablation_spec, list_ablations, registry_hash
from .resolver import (
    AblationResolutionError,
    ResolvedAblationConfig,
    resolve_ablation_config,
    validate_target_adaptation_batch,
)
from .schemas import (
    AblationBaseConfig,
    AblationSpec,
    ApprovalRecord,
    ApprovalStatus,
    AssignmentManifest,
    CandidateClassification,
    Disposition,
    ExpectedLossTerms,
    IdentityEnvelope,
    Intervention,
    InterventionKind,
    LossCoefficients,
    LossTermExpectation,
    ModelVariant,
    NotebookProvenance,
    RunMatrix,
)

__all__ = [
    "AblationBaseConfig",
    "AblationResolutionError",
    "AblationSpec",
    "ApprovalRecord",
    "ApprovalStatus",
    "ArtifactIndex",
    "ArtifactIndexEntry",
    "AssignmentManifest",
    "CandidateClassification",
    "CheckpointKind",
    "CheckpointManifest",
    "DatasetRole",
    "Disposition",
    "EquivalenceManifest",
    "ExpectedLossTerms",
    "HistoryManifest",
    "HistoryRow",
    "IdentityEnvelope",
    "Intervention",
    "InterventionKind",
    "LossCoefficients",
    "LossComponentRecord",
    "LossTermExpectation",
    "ModelVariant",
    "NotebookProvenance",
    "OutputIdentity",
    "PredictionRecord",
    "ResolvedAblationConfig",
    "RunMatrix",
    "TargetMonitoring",
    "TrainingStage",
    "get_ablation_spec",
    "list_ablations",
    "registry_hash",
    "resolve_ablation_config",
    "validate_target_adaptation_batch",
]
